/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.egresado.vista.gui;

import co.edu.eam.disenosoft.egresado.logica.excepcionNegocio.ExcepcionNegocio;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.AreaInteres;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Ciudad;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Egresado;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Empresa;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Facultad;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.InformacionAcademica;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.InformacionLaboral;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.OfertaAplicadaEgresado;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.OfertaLaboral;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Programa;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.SectorLaboral;
import co.edu.eam.disenosoft.egresado.vista.controlador.ControladorAdministrarEgresado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CAMILO
 */
public class Egresados extends javax.swing.JFrame {

	private ControladorAdministrarEgresado contEgresado;

	/**
	 * Creates new form Egresado
	 */
	public Egresados() {
		contEgresado = new ControladorAdministrarEgresado();
		initComponents();
		this.setLocationRelativeTo(this);
		// jTPEgresados.setEnabledAt(1, false);| Quitar lineas de comentarios
		// jTPEgresados.setEnabledAt(2, false); Quitar lineas de comentarios
		llenarComboFacultades();
		llenarComboProgramas();
		llenarComboInfoLab();
		llenarTabla();
		llenarComboPrograma();
		listarEmpresa();
		llenarComboProg();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jTPEgresados = new javax.swing.JTabbedPane();
        jPDatosPersonales = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLNombreDP = new javax.swing.JLabel();
        jTFNombreDP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFEmailDP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFNumTelDP = new javax.swing.JTextField();
        JTFNumCelDP = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTFPrimerApeDP = new javax.swing.JTextField();
        jLPrimerApeDP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNumDocDP = new javax.swing.JTextField();
        CBTipoDocDP = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboProg = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jBCancelarDP = new javax.swing.JButton();
        jBEditarEgresado = new javax.swing.JButton();
        jBSiguienteEgresado = new javax.swing.JButton();
        jBGuardarDatosEgresado = new javax.swing.JButton();
        jBBUscarDatosEgresado = new javax.swing.JButton();
        jPEducacion = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTFNumeroDiplomaED = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCBNivelAlcED = new javax.swing.JComboBox();
        jDCFechaGrado = new com.toedter.calendar.JDateChooser();
        jTFIdDelEgresado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCBFacultadED = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jCBProgramaED = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAAreasED = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jBCancelarED = new javax.swing.JButton();
        jBAnteriorED = new javax.swing.JButton();
        jBSigED = new javax.swing.JButton();
        jBEditarInformacionAcademica = new javax.swing.JButton();
        JBTGuardarRegEdicacion = new javax.swing.JButton();
        jBBuscarREgistroEducacion = new javax.swing.JButton();
        jPInfLaboral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jCBLaboralAcOA = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCBTipoEmpresaOA = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTFCargoEmpOA = new javax.swing.JTextField();
        jCBSectorLaboral = new javax.swing.JComboBox();
        jCFechaingreso = new com.toedter.calendar.JDateChooser();
        jCFechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jTFIdDelEgresadoB = new javax.swing.JTextField();
        jCBEmpresa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        JCBPrograma = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jBCancelarOA = new javax.swing.JButton();
        jBRegistroInfoLaboral = new javax.swing.JButton();
        jBEditarInformacionLaboral = new javax.swing.JButton();
        jBAnteriorOA = new javax.swing.JButton();
        jBBuscarInfoLaboral = new javax.swing.JButton();
        jPVerOferta = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBAplicarOferta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFNumDocAplicarOferta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTOfertaLab = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTPEgresados.setBackground(new java.awt.Color(255, 255, 255));
        jTPEgresados.setForeground(new java.awt.Color(51, 51, 51));
        jTPEgresados.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jPDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLNombreDP.setText("Nombre: ");

        jLabel8.setText("Correo Electronico");

        jLabel5.setText("Telefono Del Contacto");

        JTFNumTelDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNumTelDPKeyTyped(evt);
            }
        });

        JTFNumCelDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNumCelDPKeyTyped(evt);
            }
        });

        jLabel26.setText("Celular Del Contacto");

        jLPrimerApeDP.setText("Primer Apellido");

        jLabel2.setText("Tipo De Documento");

        jLabel3.setText("Numero Documento");

        jTFNumDocDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNumDocDPKeyTyped(evt);
            }
        });

        CBTipoDocDP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion..", "Tarjeta de identidad", "Cedula ciudadania", "Otro" }));

        jLabel9.setText("Id del Programa");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JTFNumTelDP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLNombreDP))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLPrimerApeDP))
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNombreDP)
                                    .addComponent(jTFPrimerApeDP)
                                    .addComponent(CBTipoDocDP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jTFNumDocDP)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel26)
                            .addComponent(jLabel9))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jTFEmailDP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFNumCelDP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboProg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTFEmailDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLNombreDP)
                        .addComponent(jTFNombreDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPrimerApeDP)
                            .addComponent(jTFPrimerApeDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CBTipoDocDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFNumDocDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTFNumTelDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(JTFNumCelDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCancelarDP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCancelarDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jBCancelarDP.setText("CANCELAR");
        jBCancelarDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarDPActionPerformed(evt);
            }
        });

        jBEditarEgresado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarEgresado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        jBEditarEgresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarEgresadoActionPerformed(evt);
            }
        });

        jBSiguienteEgresado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBSiguienteEgresado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        jBSiguienteEgresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteEgresadoActionPerformed(evt);
            }
        });

        jBGuardarDatosEgresado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save.png"))); // NOI18N
        jBGuardarDatosEgresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarDatosEgresadoActionPerformed(evt);
            }
        });

        jBBUscarDatosEgresado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search-24.png"))); // NOI18N
        jBBUscarDatosEgresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBUscarDatosEgresadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCancelarDP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jBBUscarDatosEgresado)
                .addGap(26, 26, 26)
                .addComponent(jBEditarEgresado)
                .addGap(26, 26, 26)
                .addComponent(jBGuardarDatosEgresado)
                .addGap(34, 34, 34)
                .addComponent(jBSiguienteEgresado)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEditarEgresado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSiguienteEgresado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBUscarDatosEgresado)
                    .addComponent(jBGuardarDatosEgresado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCancelarDP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPDatosPersonalesLayout = new javax.swing.GroupLayout(jPDatosPersonales);
        jPDatosPersonales.setLayout(jPDatosPersonalesLayout);
        jPDatosPersonalesLayout.setHorizontalGroup(
            jPDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosPersonalesLayout.createSequentialGroup()
                .addGroup(jPDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDatosPersonalesLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPDatosPersonalesLayout.setVerticalGroup(
            jPDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosPersonalesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTPEgresados.addTab("Datos Personales", jPDatosPersonales);

        jPEducacion.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Del Graduado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel15.setText("Fecha De Grado");

        jLabel17.setText("Numero del Diploma");

        jTFNumeroDiplomaED.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNumeroDiplomaEDKeyTyped(evt);
            }
        });

        jLabel18.setText("Maximo Nivel Academico");

        jCBNivelAlcED.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion...", "Diplomado", "Pregrado", "Postgrado", "Doctorado", "Postdoctorado" }));

        jTFIdDelEgresado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdDelEgresadoKeyTyped(evt);
            }
        });

        jLabel10.setText("Id del egresado  DESABILITAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jDCFechaGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFNumeroDiplomaED)
                        .addComponent(jCBNivelAlcED, 0, 165, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addComponent(jTFIdDelEgresado))
                    .addComponent(jLabel15))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(jTFIdDelEgresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDCFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNumeroDiplomaED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBNivelAlcED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Facultad");

        jCBFacultadED.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion" }));
        jCBFacultadED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFacultadEDActionPerformed(evt);
            }
        });

        jLabel13.setText("Programa");

        jCBProgramaED.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion...", "Ingenieria de software", "Ingenieria de Mecatronica", "Ingenieria Industrial", "Adminiestracion de hoteleria y turismo", "Administracion de empresas", "Administracion de contaduria publica", "Diseño visual digital", "Publicidad" }));

        jLabel27.setText("Areas de conocimiento que desearia aplicar ");

        jTAAreasED.setColumns(20);
        jTAAreasED.setRows(5);
        jScrollPane1.setViewportView(jTAAreasED);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBProgramaED, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBFacultadED, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCBFacultadED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCBProgramaED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCancelarED.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCancelarED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jBCancelarED.setText("CANCELAR");

        jBAnteriorED.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAnteriorED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        jBAnteriorED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorEDActionPerformed(evt);
            }
        });

        jBSigED.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBSigED.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        jBSigED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSigEDActionPerformed(evt);
            }
        });

        jBEditarInformacionAcademica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarInformacionAcademica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        jBEditarInformacionAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarInformacionAcademicaActionPerformed(evt);
            }
        });

        JBTGuardarRegEdicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save.png"))); // NOI18N
        JBTGuardarRegEdicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTGuardarRegEdicacionActionPerformed(evt);
            }
        });

        jBBuscarREgistroEducacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search-24.png"))); // NOI18N
        jBBuscarREgistroEducacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarREgistroEducacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCancelarED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAnteriorED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jBBuscarREgistroEducacion)
                .addGap(18, 18, 18)
                .addComponent(jBEditarInformacionAcademica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTGuardarRegEdicacion)
                .addGap(27, 27, 27)
                .addComponent(jBSigED)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCancelarED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBuscarREgistroEducacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAnteriorED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditarInformacionAcademica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTGuardarRegEdicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSigED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPEducacionLayout = new javax.swing.GroupLayout(jPEducacion);
        jPEducacion.setLayout(jPEducacionLayout);
        jPEducacionLayout.setHorizontalGroup(
            jPEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEducacionLayout.createSequentialGroup()
                .addGroup(jPEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEducacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEducacionLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPEducacionLayout.setVerticalGroup(
            jPEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEducacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPEgresados.addTab("Educacion", jPEducacion);

        jPInfLaboral.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("Situacion Laboral Actual");

        jCBLaboralAcOA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Desempleado", "Empleado", "Independiente", "Empresario" }));

        jLabel23.setText("Fecha de Ingreso");

        jLabel24.setText("Fecha de Salida");

        jLabel21.setText("Sector Laboral");

        jLabel20.setText("Tipo De Empresa");

        jCBTipoEmpresaOA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Privada", "Publica", "No aplica" }));

        jLabel22.setText("Empresa");

        jLabel25.setText("Cargo Dentro De La Empresa");

        jCBSectorLaboral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione sector laboral", "Privado", "Publico" }));

        jLabel12.setText("Id del egresado");

        jTFIdDelEgresadoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdDelEgresadoBKeyTyped(evt);
            }
        });

        jLabel1.setText("Programa academico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBLaboralAcOA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBTipoEmpresaOA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBSectorLaboral, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFIdDelEgresadoB)
                    .addComponent(jCBEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JCBPrograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23)
                        .addComponent(jCFechaingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFCargoEmpOA, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(0, 146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTFIdDelEgresadoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jCBLaboralAcOA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jCBSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jCBTipoEmpresaOA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jCBEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCargoEmpOA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCancelarOA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCancelarOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jBCancelarOA.setText("CANCELAR");

        jBRegistroInfoLaboral.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBRegistroInfoLaboral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save.png"))); // NOI18N
        jBRegistroInfoLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroInfoLaboralActionPerformed(evt);
            }
        });

        jBEditarInformacionLaboral.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarInformacionLaboral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        jBEditarInformacionLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarInformacionLaboralActionPerformed(evt);
            }
        });

        jBAnteriorOA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAnteriorOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anterior.png"))); // NOI18N
        jBAnteriorOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorOAActionPerformed(evt);
            }
        });

        jBBuscarInfoLaboral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search-24.png"))); // NOI18N
        jBBuscarInfoLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarInfoLaboralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCancelarOA)
                .addGap(38, 38, 38)
                .addComponent(jBAnteriorOA)
                .addGap(22, 22, 22)
                .addComponent(jBBuscarInfoLaboral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEditarInformacionLaboral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRegistroInfoLaboral)
                .addGap(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelarOA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBBuscarInfoLaboral, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBRegistroInfoLaboral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBEditarInformacionLaboral)
                                .addComponent(jBAnteriorOA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPInfLaboralLayout = new javax.swing.GroupLayout(jPInfLaboral);
        jPInfLaboral.setLayout(jPInfLaboralLayout);
        jPInfLaboralLayout.setHorizontalGroup(
            jPInfLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfLaboralLayout.createSequentialGroup()
                .addGroup(jPInfLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInfLaboralLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPInfLaboralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPInfLaboralLayout.setVerticalGroup(
            jPInfLaboralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfLaboralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTPEgresados.addTab("Info Laboral", jPInfLaboral);

        jPVerOferta.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplicar a oferta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jBAplicarOferta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAplicarOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apply.png"))); // NOI18N
        jBAplicarOferta.setText("APLICAR OFERTA");
        jBAplicarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAplicarOfertaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese Numero De Documento");

        jTOfertaLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Oferta", "Sector Laboral", "Area", "Cargo", "Salario", "Descripcion", "Ciudad", "Fecha Oferta", "Requisitos", "Resumen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTOfertaLab);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNumDocAplicarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAplicarOferta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNumDocAplicarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAplicarOferta)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPVerOfertaLayout = new javax.swing.GroupLayout(jPVerOferta);
        jPVerOferta.setLayout(jPVerOfertaLayout);
        jPVerOfertaLayout.setHorizontalGroup(
            jPVerOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVerOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPVerOfertaLayout.setVerticalGroup(
            jPVerOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPVerOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPEgresados.addTab("Ver Ofertas", jPVerOferta);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eam.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTPEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIdDelEgresadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdDelEgresadoKeyTyped
    	eventoNumero(evt);
    }//GEN-LAST:event_jTFIdDelEgresadoKeyTyped

    private void jTFNumeroDiplomaEDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumeroDiplomaEDKeyTyped
    	eventoNumero(evt);
    }//GEN-LAST:event_jTFNumeroDiplomaEDKeyTyped

    private void jTFIdDelEgresadoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdDelEgresadoBKeyTyped
    	eventoNumero(evt);
    }//GEN-LAST:event_jTFIdDelEgresadoBKeyTyped

	private void jBAplicarOfertaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAplicarOfertaActionPerformed
		try {
			int fila = this.jTOfertaLab.getSelectedRow();
			int idOferta = Integer.parseInt(String.valueOf(jTOfertaLab.getValueAt(fila, 0)));

			OfertaLaboral buscarOferta = contEgresado.buscarOferta(idOferta);
			Egresado buscarEgresado = contEgresado.buscarEgresado(Integer.parseInt(jTFNumDocAplicarOferta.getText()));
			
			OfertaAplicadaEgresado aplicarOferta = new OfertaAplicadaEgresado();
			
			aplicarOferta.setEgresado(buscarEgresado);
			aplicarOferta.setOfertaLaboral(buscarOferta);
			
			contEgresado.aplicarOferta(aplicarOferta);
			
			JOptionPane.showMessageDialog(null, "Aplicacion a la oferta con exito");
			
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void jBBuscarInfoLaboralActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			InformacionLaboral infoLab = contEgresado
					.buscarInformacionLaboral(Integer.parseInt(jTFIdDelEgresadoB.getText()));

			if (infoLab != null) {
				jTFIdDelEgresadoB.setText(Integer.toString(infoLab.getEgresado().getId()));
				jCBLaboralAcOA.setSelectedItem(infoLab.getSitucionLaboral());
				jCBSectorLaboral.setSelectedItem(infoLab.getSectorLaboral());
				jCBTipoEmpresaOA.setSelectedItem(infoLab.getTipoEmpresa());
				jCBEmpresa.setSelectedItem(infoLab.getEmpresa());
				jTFCargoEmpOA.setText(infoLab.getCargoEmpresa());
				jCFechaingreso.setDate(infoLab.getFechaIngreso());
				jCFechaSalida.setDate(infoLab.getFechaSalida());
				JCBPrograma.setSelectedItem(infoLab.getPrograma());
			} else {
				JOptionPane.showMessageDialog(null, "No existe registro laboral de este egresado");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void JTFNumTelDPKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_JTFNumTelDPKeyTyped
		eventoNumero(evt);
	}// GEN-LAST:event_JTFNumTelDPKeyTyped

	private void JTFNumCelDPKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_JTFNumCelDPKeyTyped
		eventoNumero(evt);
	}// GEN-LAST:event_JTFNumCelDPKeyTyped

	private void jTFNumDocDPKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFNumDocDPKeyTyped
		eventoNumero(evt);
	}// GEN-LAST:event_jTFNumDocDPKeyTyped

	private void jTFIdProgramDPKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFIdProgramDPKeyTyped
		eventoNumero(evt);
	}// GEN-LAST:event_jTFIdProgramDPKeyTyped

	private void jBCancelarDPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCancelarDPActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBCancelarDPActionPerformed

	private void jBEditarEgresadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarEgresadoActionPerformed
		try {

			Egresado egresado = new Egresado();

			
			
			Programa idProg = (Programa) jComboProg.getSelectedItem();
			Programa prog = contEgresado.buscarPrograma(idProg.getIdPrograma());
			if (prog != null) {
				egresado.setId(Integer.parseInt(jTFNumDocDP.getText()));
				egresado.setApellido(jTFPrimerApeDP.getText());
				egresado.setCelular(JTFNumCelDP.getText());
				egresado.setEmail(jTFEmailDP.getText());
				egresado.setNombre(jTFNombreDP.getText());
				egresado.setTelefono(JTFNumTelDP.getText());
				egresado.setPrograma(prog);
				egresado.setTipoDoc((String) CBTipoDocDP.getSelectedItem());

				contEgresado.editarEgresado(egresado);
				JOptionPane.showMessageDialog(null, "Egresado registrado con exito");
			} else {
				JOptionPane.showMessageDialog(null, "El programa academico no exite");
			}

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_jBEditarEgresadoActionPerformed

	private void jBSiguienteEgresadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBSiguienteEgresadoActionPerformed
		jTPEgresados.setSelectedIndex(1);
	
	}// GEN-LAST:event_jBSiguienteEgresadoActionPerformed

	private void jCBFacultadEDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCBFacultadEDActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jCBFacultadEDActionPerformed

	private void jBAnteriorEDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAnteriorEDActionPerformed
		jTPEgresados.setSelectedIndex(0);
		
	}// GEN-LAST:event_jBAnteriorEDActionPerformed

	private void jBSigEDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBSigEDActionPerformed
		jTPEgresados.setSelectedIndex(2);
		
	}// GEN-LAST:event_jBSigEDActionPerformed

	private void jBEditarInformacionAcademicaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarInformacionAcademicaActionPerformed
		try {
			if(jTFIdDelEgresado.getText().length()<=10){
				InformacionAcademica infoAc = new InformacionAcademica();

				Egresado egre = contEgresado.buscarEgresado(Integer.parseInt(jTFIdDelEgresado.getText()));

				infoAc.setAreaConocimiento(jTAAreasED.getText());
				infoAc.setEgresado(egre);
				infoAc.setFacultad((String) jCBFacultadED.getSelectedItem());
				infoAc.setFechaGrado(jDCFechaGrado.getDate());
				infoAc.setMaximoNivelAcademico((String) jCBNivelAlcED.getSelectedItem());
				infoAc.setNumeroDiploma(jTFNumeroDiplomaED.getText());
				infoAc.setProgramaAcademico((String) jCBProgramaED.getSelectedItem());

				contEgresado.editarInformacionAcademica(infoAc);

				JOptionPane.showMessageDialog(null, "Informacion academica del egresado editada con exito");
			}else{
				JOptionPane.showMessageDialog(null, "Verifique que el id del egresado no obtenga mas de 10 caracteres");
			}
			

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_jBEditarInformacionAcademicaActionPerformed

	private void JBTGuardarRegEdicacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JBTGuardarRegEdicacionActionPerformed
		try {
			InformacionAcademica infoAc = new InformacionAcademica();

			Egresado egre = contEgresado.buscarEgresado(Integer.parseInt(jTFIdDelEgresado.getText()));

			infoAc.setAreaConocimiento(jTAAreasED.getText());
			infoAc.setEgresado(egre);
			infoAc.setFacultad((String) jCBFacultadED.getSelectedItem());
			infoAc.setFechaGrado(jDCFechaGrado.getDate());
			infoAc.setMaximoNivelAcademico((String) jCBNivelAlcED.getSelectedItem());
			infoAc.setNumeroDiploma(jTFNumeroDiplomaED.getText());
			infoAc.setProgramaAcademico((String) jCBProgramaED.getSelectedItem());

			contEgresado.crearInformacionAcademica(infoAc);
			limpiarEducacion();
			JOptionPane.showMessageDialog(null, "Informacion academica del egresado creada con exito");

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_JBTGuardarRegEdicacionActionPerformed

	private void jBBuscarREgistroEducacionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarREgistroEducacionActionPerformed
		int egre = Integer.parseInt(jTFIdDelEgresado.getText());
		InformacionAcademica infoAc = contEgresado.buscarInformacionAcademica(egre);
		if (infoAc != null) {
			jCBFacultadED.setSelectedItem(infoAc.getFacultad());
			jCBProgramaED.setSelectedItem(infoAc.getProgramaAcademico());
			jTAAreasED.setText(infoAc.getAreaConocimiento());
			jDCFechaGrado.setDate(infoAc.getFechaGrado());
			jTFNumeroDiplomaED.setText(infoAc.getNumeroDiploma());
			jCBNivelAlcED.setSelectedItem(infoAc.getMaximoNivelAcademico());
			
		} else {
			JOptionPane.showMessageDialog(null, "La informacion academica del egresado no existe");
		}
	}// GEN-LAST:event_jBBuscarREgistroEducacionActionPerformed

	private void jBAnteriorOAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAnteriorOAActionPerformed
		jTPEgresados.setSelectedIndex(1);
	}// GEN-LAST:event_jBAnteriorOAActionPerformed

	private void jBRegistroInfoLaboralActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBRegistroInfoLaboralActionPerformed
		try {
			InformacionLaboral infoLab = new InformacionLaboral();
			Egresado egre = contEgresado.buscarEgresado(Integer.parseInt(jTFIdDelEgresadoB.getText()));

			infoLab.setCargoEmpresa(jTFCargoEmpOA.getText());
			infoLab.setEgresado(egre);
			infoLab.setFechaIngreso(jCFechaingreso.getDate());
			infoLab.setFechaSalida(jCFechaSalida.getDate());
			Empresa empresa = (Empresa) jCBEmpresa.getSelectedItem();
			infoLab.setEmpresa(empresa);
			infoLab.setSectorLaboral((String) jCBSectorLaboral.getSelectedItem());
			infoLab.setSitucionLaboral((String) jCBLaboralAcOA.getSelectedItem());
			infoLab.setTipoEmpresa((String) jCBTipoEmpresaOA.getSelectedItem());
			Programa programa = (Programa) JCBPrograma.getSelectedItem();
			infoLab.setPrograma(programa);
			contEgresado.crearInformacionLaboral(infoLab);
			limoiarInfLaboral();
			JOptionPane.showMessageDialog(null, "Informacion laboral del egresado guardada con exito");

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void jBEditarInformacionLaboralActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarInformacionLaboralActionPerformed
		try {
			InformacionLaboral infoLab = new InformacionLaboral();
			Egresado egre = contEgresado.buscarEgresado(Integer.parseInt(jTFIdDelEgresadoB.getText()));

			infoLab.setCargoEmpresa(jTFCargoEmpOA.getText());
			infoLab.setEgresado(egre);
			infoLab.setFechaIngreso(jCFechaingreso.getDate());
			infoLab.setFechaSalida(jCFechaSalida.getDate());
			Empresa empresa = (Empresa) jCBEmpresa.getSelectedItem();
			infoLab.setEmpresa(empresa);
			infoLab.setSectorLaboral((String) jCBSectorLaboral.getSelectedItem());
			infoLab.setSitucionLaboral((String) jCBLaboralAcOA.getSelectedItem());
			infoLab.setTipoEmpresa((String) jCBTipoEmpresaOA.getSelectedItem());
			Programa programa = (Programa) JCBPrograma.getSelectedItem();
			infoLab.setPrograma(programa);
			contEgresado.editarInformacionLaboral(infoLab);

			JOptionPane.showMessageDialog(null, "Informacion laboral del egresado editada con exito");

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void jBBUscarDatosEgresadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBUscarDatosEgresadoActionPerformed
	try {
		
		if(!jTFNumDocDP.getText().isEmpty()){
			int idEgresado = Integer.parseInt(jTFNumDocDP.getText());
			Egresado egres = contEgresado.buscarEgresado(idEgresado);

			jTFNombreDP.setText(egres.getNombre());
			jTFPrimerApeDP.setText(egres.getApellido());
			CBTipoDocDP.setSelectedItem(egres.getTipoDoc());
			jTFNumDocDP.setText(Integer.toString(egres.getId()));
			jTFEmailDP.setText(egres.getEmail());
			JTFNumTelDP.setText(egres.getTelefono());
			JTFNumCelDP.setText(egres.getCelular());
			jComboProg.setSelectedItem(egres.getPrograma());
		}else{
			JOptionPane.showMessageDialog(null, "Por favor verifique que el campo 'Numero de documento'"
					+"\n" + "Se encuentre lleno");
		}
			
		
	} catch (Exception e) {
		// TODO: handle exception
	}
	}// GEN-LAST:event_jBBUscarDatosEgresadoActionPerformed

	private void jBGuardarDatosEgresadoActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if(jTFNumDocDP.getText().length()<= 10 &&
					JTFNumCelDP.getText().length() <= 10 &&
					JTFNumTelDP.getText().length() <=7 ){
				
				co.edu.eam.disenosoft.egresado.persistencia.entidades.Egresado egresado = new co.edu.eam.disenosoft.egresado.persistencia.entidades.Egresado();

				Programa idProg = (Programa) jComboProg.getSelectedItem();
				Programa prog = contEgresado.buscarPrograma(idProg.getIdPrograma());
				
					egresado.setId(Integer.parseInt(jTFNumDocDP.getText()));
					egresado.setApellido(jTFPrimerApeDP.getText());
					egresado.setCelular(JTFNumCelDP.getText());
					egresado.setEmail(jTFEmailDP.getText());
					egresado.setNombre(jTFNombreDP.getText());
					egresado.setTelefono(JTFNumTelDP.getText());
					egresado.setPrograma(prog);
					egresado.setTipoDoc((String) CBTipoDocDP.getSelectedItem());

					contEgresado.crearEgresado(egresado);
					limpiarCamposDatosPer();
					JOptionPane.showMessageDialog(null, "Egresado registrado con exito");
					
					jTFIdDelEgresado.setText(jTFNumDocDP.getText());
					jTFIdDelEgresadoB.setText(jTFNumDocDP.getText());
				
			}else{
				JOptionPane.showMessageDialog(null, "Verifique que los campos Telefono,Celular y Numero del diploma no obtengan "
						+"\n"+ "mas de 10 caracteres");
			}
			
		
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_jBGuardarDatosEgresadoActionPerformed

	/**
	 * LLena el combo box de facultad con una lista de facultades regsitradas
	 */
	public void llenarComboFacultades() {
		try {
			jCBFacultadED.removeAllItems();
			jCBFacultadED.addItem("Selecciones una facultad");
			List<Facultad> lisFac = contEgresado.listaFacultades();

			for (Facultad facultad : lisFac) {
				jCBFacultadED.addItem(facultad.getNombreFacultad());
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * LLena el combo box de programa con una lista de programas academicos
	 * regsitrados
	 */
	public void llenarComboProgramas() {
		try {
			jCBProgramaED.removeAllItems();
			jCBProgramaED.addItem("Selecciones un programa");
			List<Programa> lisPro = contEgresado.listaProgramas();

			for (Programa programa : lisPro) {
				jCBProgramaED.addItem(programa.getNombrePrograma());
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * LLena el combo box de programa con una lista de programas academicos
	 * regsitrados
	 */
	public void llenarComboProg() {
		try {
			JCBPrograma.removeAllItems();
			JCBPrograma.addItem("Selecciones un programa");
			List<Programa> lisPro = contEgresado.listaProgramas();

			for (Programa programa : lisPro) {
				JCBPrograma.addItem(programa);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * llena el combo de la informacion laboral con los secores laborales
	 * creados en el sistema
	 */
	public void llenarComboInfoLab() {
		try {
			jCBSectorLaboral.removeAllItems();
			jCBSectorLaboral.addItem("Selecciones un sector laboral");
			List<SectorLaboral> lisSec = contEgresado.listaLaboral();

			for (SectorLaboral sect : lisSec) {
				jCBSectorLaboral.addItem(sect.getNombreSector());
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * llena la tabla con los datos de la oferta a listar
	 */
	public void llenarTabla() {
		try {
			DefaultTableModel df = (DefaultTableModel) jTOfertaLab.getModel();
			df.setRowCount(0);

			List<OfertaLaboral> listOferta = contEgresado.listaOferta();

			for (int i = 0; i < listOferta.size(); i++) {
				AreaInteres buscarArea = contEgresado.buscarArea(listOferta.get(i).getIdArea().getIdArea());
				Ciudad buscarCiudad = contEgresado.buscarCiudad(listOferta.get(i).getIdCiudad().getIdCiudad());
				Empresa buscarEmpresa = contEgresado.buscarEmpresa(listOferta.get(i).getIdempresa().getId());
				if (listOferta.get(i).isCerrarOferta() == false) {
					df.addRow(new Object[] { listOferta.get(i).getIdOferta(),
							buscarEmpresa.getIdSectorLaboral().getNombreSector(), buscarArea.getNombre(),
							listOferta.get(i).getCargoOfrecer(), listOferta.get(i).getSalario(),
							listOferta.get(i).getDescripcionOferta(), buscarCiudad.getNombre(),
							listOferta.get(i).getFechaoferta(), listOferta.get(i).getRequisitoOferta(),
							listOferta.get(i).getResumen() });
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * evento para validar los campos numericos
	 * @param evt objeto  del eveno
	 */
	public void eventoNumero(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();
		 if(Character.isLetter(c)) {
		//if (c < '0' || c > '9') {
			getToolkit().beep();
			evt.consume();
			JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");
		}
	}

	/**
	 * llena el combo cargando los programas que han sido registrados
	 */
	public void llenarComboPrograma(){
		try {
			List<Programa> listaPrograma = contEgresado.listaPrograma();
			jComboProg.removeAllItems();
			for(Programa programa: listaPrograma){
				jComboProg.addItem(programa);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	
	/**
	 * lista una empresa que ha sido buscada 
	 * @param oferta la oferta buscada a la cual se le busca la 
	 * empresa 
	 */
	public void listarEmpresa() {
		try {
			jCBEmpresa.removeAllItems();
			List<Empresa> listaEmpresa = contEgresado.listaEmpresa();
			for (int i = 0; i < listaEmpresa.size(); i++) {
				jCBEmpresa.addItem(listaEmpresa.get(i));
			}
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
	
	/**
	 * limpia los campos de los datos del empleado
	 */
	public void limpiarCamposDatosPer(){
		jTFNombreDP.setText(null);
		jTFPrimerApeDP.setText(null);
		CBTipoDocDP.setSelectedIndex(0);
		jTFNumDocDP.setText(null);
		jTFEmailDP.setText(null);
		JTFNumTelDP.setText(null);
		JTFNumCelDP.setText(null);
		jComboProg.setSelectedIndex(0);
	}
	
	/**
	 * limpia los campos de la pestaña educacion
	 */
	public void limpiarEducacion(){
		jTFIdDelEgresado.setText(null);
		jTFIdDelEgresadoB.setText(null);
		jCBFacultadED.setSelectedItem(null);
		jCBProgramaED.setSelectedItem(null);
		jTAAreasED.setText(null);
		jDCFechaGrado.setDate(null);
		jTFNumeroDiplomaED.setText(null);
		jCBNivelAlcED.setSelectedIndex(0);
	}
	
	/**
	 * limpia los campos de informacion laboral
	 */
	public void limoiarInfLaboral(){
		jTFIdDelEgresadoB.setText(null);
		jCBLaboralAcOA.setSelectedIndex(0);
		jCBSectorLaboral.setSelectedIndex(0);
		jCBTipoEmpresaOA.setSelectedIndex(0);
		jCBEmpresa.setSelectedIndex(0);
		jTFCargoEmpOA.setText(null);
		jCFechaingreso.setDate(null);
		jCFechaSalida.setDate(null);
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBTipoDocDP;
    private javax.swing.JButton JBTGuardarRegEdicacion;
    private javax.swing.JComboBox JCBPrograma;
    private javax.swing.JTextField JTFNumCelDP;
    private javax.swing.JTextField JTFNumTelDP;
    private javax.swing.JButton jBAnteriorED;
    private javax.swing.JButton jBAnteriorOA;
    private javax.swing.JButton jBAplicarOferta;
    private javax.swing.JButton jBBUscarDatosEgresado;
    private javax.swing.JButton jBBuscarInfoLaboral;
    private javax.swing.JButton jBBuscarREgistroEducacion;
    private javax.swing.JButton jBCancelarDP;
    private javax.swing.JButton jBCancelarED;
    private javax.swing.JButton jBCancelarOA;
    private javax.swing.JButton jBEditarEgresado;
    private javax.swing.JButton jBEditarInformacionAcademica;
    private javax.swing.JButton jBEditarInformacionLaboral;
    private javax.swing.JButton jBGuardarDatosEgresado;
    private javax.swing.JButton jBRegistroInfoLaboral;
    private javax.swing.JButton jBSigED;
    private javax.swing.JButton jBSiguienteEgresado;
    private javax.swing.JComboBox jCBEmpresa;
    private javax.swing.JComboBox<String> jCBFacultadED;
    private javax.swing.JComboBox<String> jCBLaboralAcOA;
    private javax.swing.JComboBox<String> jCBNivelAlcED;
    private javax.swing.JComboBox<String> jCBProgramaED;
    private javax.swing.JComboBox<String> jCBSectorLaboral;
    private javax.swing.JComboBox<String> jCBTipoEmpresaOA;
    private com.toedter.calendar.JDateChooser jCFechaSalida;
    private com.toedter.calendar.JDateChooser jCFechaingreso;
    private javax.swing.JComboBox jComboProg;
    private com.toedter.calendar.JDateChooser jDCFechaGrado;
    private javax.swing.JLabel jLNombreDP;
    private javax.swing.JLabel jLPrimerApeDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDatosPersonales;
    private javax.swing.JPanel jPEducacion;
    private javax.swing.JPanel jPInfLaboral;
    private javax.swing.JPanel jPVerOferta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAAreasED;
    private javax.swing.JTextField jTFCargoEmpOA;
    private javax.swing.JTextField jTFEmailDP;
    private javax.swing.JTextField jTFIdDelEgresado;
    private javax.swing.JTextField jTFIdDelEgresadoB;
    private javax.swing.JTextField jTFNombreDP;
    private javax.swing.JTextField jTFNumDocAplicarOferta;
    private javax.swing.JTextField jTFNumDocDP;
    private javax.swing.JTextField jTFNumeroDiplomaED;
    private javax.swing.JTextField jTFPrimerApeDP;
    private javax.swing.JTable jTOfertaLab;
    private javax.swing.JTabbedPane jTPEgresados;
    // End of variables declaration//GEN-END:variables
}
