/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.egresado.vista.gui;

import java.awt.event.KeyEvent;
import java.awt.geom.Area;

import javax.swing.JOptionPane;

import co.edu.eam.disenosoft.egresado.logica.excepcionNegocio.ExcepcionNegocio;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.AreaInteres;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Facultad;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Programa;
import co.edu.eam.disenosoft.egresado.vista.controlador.ControladorAdministrarParametrica;

/**
 *
 * @author laura posada
 */
public class Parametrica extends javax.swing.JFrame {

	private ControladorAdministrarParametrica contParametrica;

	/**
	 * Creates new form Parametrica
	 */
	public Parametrica() {
		contParametrica = new ControladorAdministrarParametrica();
		initComponents();
		this.setLocationRelativeTo(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPGestionesParametrica = new javax.swing.JTabbedPane();
        jPGestionPrograma = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBCrearGestionPrograma = new javax.swing.JButton();
        jBEditarGestionPrograma = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFIdPrograma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFIdFacultadPro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFNombrePrograma = new javax.swing.JTextField();
        jPGestionAreas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBCrearGestionAreas = new javax.swing.JButton();
        jBEditarGestionArea = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFIdAreaInteres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFNombreAreaInteres = new javax.swing.JTextField();
        jPGestionFacultad = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBCrearGestionFacultad = new javax.swing.JButton();
        jBEditarGestionFacultad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFIdFacultad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFNombreFacultad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Informacion Parametrica");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eam.jpg"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPGestionPrograma.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBCrearGestionPrograma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCrearGestionPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jBCrearGestionPrograma.setText("CREAR");
        jBCrearGestionPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearGestionProgramaActionPerformed(evt);
            }
        });

        jBEditarGestionPrograma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarGestionPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jBEditarGestionPrograma.setText("EDITAR");
        jBEditarGestionPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarGestionProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCrearGestionPrograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jBEditarGestionPrograma)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearGestionPrograma)
                    .addComponent(jBEditarGestionPrograma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Programa"));

        jLabel4.setText("Id Programa");

        jTFIdPrograma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdProgramaKeyTyped(evt);
            }
        });

        jLabel5.setText("Id facultad");

        jTFIdFacultadPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdFacultadProKeyTyped(evt);
            }
        });

        jLabel6.setText("Nombre programa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNombrePrograma))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFIdPrograma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFIdFacultadPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFIdPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFIdFacultadPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPGestionProgramaLayout = new javax.swing.GroupLayout(jPGestionPrograma);
        jPGestionPrograma.setLayout(jPGestionProgramaLayout);
        jPGestionProgramaLayout.setHorizontalGroup(
            jPGestionProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGestionProgramaLayout.createSequentialGroup()
                .addGroup(jPGestionProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGestionProgramaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPGestionProgramaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPGestionProgramaLayout.setVerticalGroup(
            jPGestionProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGestionProgramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPGestionesParametrica.addTab("Gestion de Programa", jPGestionPrograma);

        jPGestionAreas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBCrearGestionAreas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCrearGestionAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jBCrearGestionAreas.setText("CREAR");
        jBCrearGestionAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearGestionAreasActionPerformed(evt);
            }
        });

        jBEditarGestionArea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarGestionArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jBEditarGestionArea.setText("EDITAR");
        jBEditarGestionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarGestionAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCrearGestionAreas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jBEditarGestionArea)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearGestionAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditarGestionArea))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Areas de interes"));

        jLabel7.setText("Id Area de Interes");

        jTFIdAreaInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdAreaInteresKeyTyped(evt);
            }
        });

        jLabel8.setText("Nombre Area de Interes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jTFIdAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombreAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(jTFIdAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNombreAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPGestionAreasLayout = new javax.swing.GroupLayout(jPGestionAreas);
        jPGestionAreas.setLayout(jPGestionAreasLayout);
        jPGestionAreasLayout.setHorizontalGroup(
            jPGestionAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGestionAreasLayout.createSequentialGroup()
                .addGroup(jPGestionAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGestionAreasLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPGestionAreasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPGestionAreasLayout.setVerticalGroup(
            jPGestionAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGestionAreasLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPGestionesParametrica.addTab("Gestionar Areas de Interes", jPGestionAreas);

        jPGestionFacultad.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBCrearGestionFacultad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBCrearGestionFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jBCrearGestionFacultad.setText("CREAR");
        jBCrearGestionFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearGestionFacultadActionPerformed(evt);
            }
        });

        jBEditarGestionFacultad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarGestionFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jBEditarGestionFacultad.setText("EDITAR");
        jBEditarGestionFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarGestionFacultadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jBCrearGestionFacultad)
                .addGap(74, 74, 74)
                .addComponent(jBEditarGestionFacultad))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearGestionFacultad)
                    .addComponent(jBEditarGestionFacultad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Facultad"));

        jLabel2.setText("Id facultad");

        jLabel3.setText("Nombre de la facultad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jTFIdFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jTFIdFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPGestionFacultadLayout = new javax.swing.GroupLayout(jPGestionFacultad);
        jPGestionFacultad.setLayout(jPGestionFacultadLayout);
        jPGestionFacultadLayout.setHorizontalGroup(
            jPGestionFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGestionFacultadLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPGestionFacultadLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPGestionFacultadLayout.setVerticalGroup(
            jPGestionFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGestionFacultadLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPGestionesParametrica.addTab("Gestionar Facultades", jPGestionFacultad);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPGestionesParametrica, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPGestionesParametrica, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIdProgramaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdProgramaKeyTyped
        eventoNumero(evt);
    }//GEN-LAST:event_jTFIdProgramaKeyTyped

    private void jTFIdFacultadProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdFacultadProKeyTyped
        eventoNumero(evt);
    }//GEN-LAST:event_jTFIdFacultadProKeyTyped

    private void jTFIdAreaInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdAreaInteresKeyTyped
        eventoNumero(evt);
    }//GEN-LAST:event_jTFIdAreaInteresKeyTyped

    private void jBCrearGestionAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearGestionAreasActionPerformed
        
    	try{
    		
    		AreaInteres area = new AreaInteres();
    		area.setIdArea(Integer.parseInt(jTFIdAreaInteres.getText()));
    		area.setNombre(jTFNombreAreaInteres.getText());
    		
    		contParametrica.crearAreaInteres(area);
    		limpiarCamposAreaInteres();
    		JOptionPane.showMessageDialog(null, "Area de interes creada con exito");
    		
    	}catch (ExcepcionNegocio ex) {
    			JOptionPane.showMessageDialog(null, ex.getMessage());
    	}catch (Exception e) {
			e.printStackTrace();
		}
    	
    }//GEN-LAST:event_jBCrearGestionAreasActionPerformed

    private void jBEditarGestionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarGestionAreaActionPerformed
        
    	try{
    		
    		AreaInteres area = new AreaInteres();
    		
    		area.setIdArea(Integer.parseInt(jTFIdAreaInteres.getText()));
    		area.setNombre(jTFNombreAreaInteres.getText());
    		
    		contParametrica.editarAreaInteres(area);
    		
    		JOptionPane.showMessageDialog(null, "Area de interes editada con exito");
    		
    	}catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		}catch (Exception e) {
			e.printStackTrace();
		}
    	
    }//GEN-LAST:event_jBEditarGestionAreaActionPerformed

	private void jBCrearGestionProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCrearGestionProgramaActionPerformed
		try {
			Programa pro = new Programa();
			Facultad fac = contParametrica.buscarFacultad(Integer.parseInt(jTFIdFacultadPro.getText()));
			
			pro.setIdFacultad(fac);
			pro.setIdPrograma(Integer.parseInt(jTFIdPrograma.getText()));
			pro.setNombrePrograma(jTFNombrePrograma.getText());
			
			contParametrica.crearPrograma(pro);
			limpiarCamposPrograma();
			JOptionPane.showMessageDialog(null, "Programa creado con exito");
		} catch (ExcepcionNegocio ex) {

		}catch (Exception e) {
			
		}

	}// GEN-LAST:event_jBCrearGestionProgramaActionPerformed

	private void jBEditarGestionProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarGestionProgramaActionPerformed

		try{
			Programa prog = new  Programa();
			
			Facultad fac = contParametrica.buscarFacultad(Integer.parseInt(jTFIdFacultadPro.getText()));
			
			prog.setIdFacultad(fac);
			prog.setIdPrograma(Integer.parseInt(jTFIdPrograma.getText()));
			prog.setNombrePrograma(jTFNombrePrograma.getText());
			
			contParametrica.editarPrograma(prog);
			limpiarCamposPrograma();
			JOptionPane.showMessageDialog(null, "Programa editado con exito");
			
		}catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		}catch (Exception e) {
			e.printStackTrace();
		}	
		
	}// GEN-LAST:event_jBEditarGestionProgramaActionPerformed
	
	private void jBCrearGestionFacultadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCrearGestionFacultadActionPerformed

		try {
			Facultad fac = new Facultad();
			fac.setIdFacultad(Integer.parseInt(jTFIdFacultad.getText()));
			fac.setNombreFacultad(jTFNombreFacultad.getText());

			contParametrica.crearFacultad(fac);
			limpiarCamposFacultad();
			JOptionPane.showMessageDialog(null, "Facultad creada");

		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_jBCrearGestionFacultadActionPerformed

	private void jBEditarGestionFacultadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarGestionFacultadActionPerformed

		try {

			Facultad fac = new Facultad();

			fac.setIdFacultad(Integer.parseInt(jTFIdFacultad.getText()));
			fac.setNombreFacultad(jTFNombreFacultad.getText());

			contParametrica.editarFacultad(fac);
			limpiarCamposFacultad();
			JOptionPane.showMessageDialog(null, "Facultad editada con exito");

		} catch (ExcepcionNegocio e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}// GEN-LAST:event_jBEditarGestionFacultadActionPerformed

	private void jTFIdFacultadKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFIdFacultadKeyTyped
		eventoNumero(evt);
	}// GEN-LAST:event_jTFIdFacultadKeyTyped

	public void eventoNumero(java.awt.event.KeyEvent evt) {
		char c = evt.getKeyChar();

		 if(Character.isLetter(c)) {
		//if (c < '0' || c > '9') {
			getToolkit().beep();

			evt.consume();

			JOptionPane.showMessageDialog(null, "Ingresa Solo Numeros");

		}
	}

	public void limpiarCamposFacultad() {
		jTFIdFacultad.setText(null);
		jTFNombreFacultad.setText(null);
	}
	
	public void limpiarCamposPrograma(){
		jTFIdFacultadPro.setText(null);
		jTFIdPrograma.setText(null);
		jTFNombrePrograma.setText(null);
	}
	
	public void limpiarCamposAreaInteres(){
		jTFIdAreaInteres.setText(null);
		jTFNombreAreaInteres.setText(null);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearGestionAreas;
    private javax.swing.JButton jBCrearGestionFacultad;
    private javax.swing.JButton jBCrearGestionPrograma;
    private javax.swing.JButton jBEditarGestionArea;
    private javax.swing.JButton jBEditarGestionFacultad;
    private javax.swing.JButton jBEditarGestionPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPGestionAreas;
    private javax.swing.JPanel jPGestionFacultad;
    private javax.swing.JPanel jPGestionPrograma;
    private javax.swing.JTabbedPane jPGestionesParametrica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTFIdAreaInteres;
    private javax.swing.JTextField jTFIdFacultad;
    private javax.swing.JTextField jTFIdFacultadPro;
    private javax.swing.JTextField jTFIdPrograma;
    private javax.swing.JTextField jTFNombreAreaInteres;
    private javax.swing.JTextField jTFNombreFacultad;
    private javax.swing.JTextField jTFNombrePrograma;
    // End of variables declaration//GEN-END:variables
}
