/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.egresado.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

import co.edu.eam.disenosoft.egresado.persistencia.entidades.AreaInteres;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Ciudad;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Empresa;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.InformacionLaboral;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.OfertaLaboral;
import co.edu.eam.disenosoft.egresado.persistencia.entidades.Programa;
import co.edu.eam.disenosoft.egresado.vista.controlador.ControladorReportes;

/**
 *
 * @author laura posada
 */
public class ReportesEstadisticas extends javax.swing.JFrame {

	private ControladorReportes contReportes;

	/**
	 * Creates new form ReportesEstadisticas
	 */
	public ReportesEstadisticas() {
		contReportes = new ControladorReportes();
		initComponents();
		this.setLocationRelativeTo(this);
		reporteEgresadosOcupacion();
		ofertasAbriertas();
		llenarTablaEmpleadosEmpresa();
		llenarTablaOfertasPrograma();
		listaPrgrama();
		listaPrgramaAcademico();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTPReportesYEstadisticas2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPGraficaTipoOcupacion = new javax.swing.JPanel();
        jCPrograma = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPofertaabierta = new javax.swing.JPanel();
        jCProgramaAcademico = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEmpleadoEmpresa = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTreporteOfertaProgramas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Reporte y Estaditicas");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPGraficaTipoOcupacion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPGraficaTipoOcupacionLayout = new javax.swing.GroupLayout(jPGraficaTipoOcupacion);
        jPGraficaTipoOcupacion.setLayout(jPGraficaTipoOcupacionLayout);
        jPGraficaTipoOcupacionLayout.setHorizontalGroup(
            jPGraficaTipoOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPGraficaTipoOcupacionLayout.setVerticalGroup(
            jPGraficaTipoOcupacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jCPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCProgramaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGraficaTipoOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jCPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPGraficaTipoOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTPReportesYEstadisticas2.addTab("Egresados por tipo de ocupacion", jPanel3);

        jPofertaabierta.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPofertaabiertaLayout = new javax.swing.GroupLayout(jPofertaabierta);
        jPofertaabierta.setLayout(jPofertaabiertaLayout);
        jPofertaabiertaLayout.setHorizontalGroup(
            jPofertaabiertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPofertaabiertaLayout.setVerticalGroup(
            jPofertaabiertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        jCProgramaAcademico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCProgramaAcademicoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPofertaabierta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCProgramaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jCProgramaAcademico, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPofertaabierta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTPReportesYEstadisticas2.addTab("Numero de ofertas abiertas", jPanel4);

        jTEmpleadoEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Programa", "Cargo", "Fecha de entrada"
            }
        ));
        jScrollPane1.setViewportView(jTEmpleadoEmpresa);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPReportesYEstadisticas2.addTab("Empleados por empresa", jPanel7);

        jTreporteOfertaProgramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Fecha de publicacion", "Fecha de cierre", "Cargo", "Salario", "Resumen"
            }
        ));
        jScrollPane3.setViewportView(jTreporteOfertaProgramas);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPReportesYEstadisticas2.addTab("Oferta por programa", jPanel8);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eam.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTPReportesYEstadisticas2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTPReportesYEstadisticas2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCProgramaItemStateChanged
    	    	
    	ChartPanel panel;
		try {
			
			Programa programa = (Programa) jCPrograma.getSelectedItem();
			
			List<InformacionLaboral> listaInfoLab = contReportes.listaInfomracionLaboralPrograma(programa);

			jPGraficaTipoOcupacion.removeAll();
			
			double empleado = 0;
			double desempleado = 0;
			double independiente = 0;
			double empresario = 0;

			int contadorEmpleado = 0;
			int contadordDesempleado = 0;
			int contadorIndependiente = 0;
			int contadorEmpresario = 0;

			for (int i = 0; i < listaInfoLab.size(); i++) {
				if (listaInfoLab.get(i).getSitucionLaboral().equals("Empleado")) {
					contadorEmpleado++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Desempleado")) {
					contadordDesempleado++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Independiente")) {
					contadorIndependiente++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Empresario")) {
					contadorEmpresario++;
				} else {
					JOptionPane.showMessageDialog(null, "No hay empleados registrados");
				}

				empleado = (contadorEmpleado * 100) / listaInfoLab.size();
				desempleado = (contadordDesempleado * 100) / listaInfoLab.size();
				independiente = (contadorIndependiente * 100) / listaInfoLab.size();
				empresario = (contadorEmpresario * 100) / listaInfoLab.size();
			}
			DefaultPieDataset ds = new DefaultPieDataset();
			ds.setValue("Empleado: " + empleado + "%", empleado);
			ds.setValue("Desempleado: " + desempleado + "%", desempleado);
			ds.setValue("Independiente: " + independiente + "%", independiente);
			ds.setValue("Empresario: " + empresario + "%", empresario);

			JFreeChart jf = ChartFactory.createPieChart3D("Reporte de egresados por tipo de ocupación", ds, true, true,
					true);

			panel = new ChartPanel(jf);
			panel.setBounds(20, 50, 720, 350);

			jPGraficaTipoOcupacion.add(panel);

		} catch (Exception e) {
			// TODO: handle exception
		}

        
        
    }//GEN-LAST:event_jCProgramaItemStateChanged

    private void jCProgramaAcademicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCProgramaAcademicoItemStateChanged
    	ChartPanel panel;
		try {
			
			Programa programa = (Programa) jCProgramaAcademico.getSelectedItem();
			
			List<OfertaLaboral> listaOfertaLab = contReportes.listaOfertaPrograma(programa);

			
			
			int contador = 0;
			AreaInteres areaAnterior = null;
			DefaultCategoryDataset ds = new DefaultCategoryDataset();

			for (int i = 0; i < listaOfertaLab.size(); i++) {
				jPofertaabierta.removeAll();
				// Validacion de oferta
				if (listaOfertaLab.get(i).isCerrarOferta() == false) {
					areaAnterior = listaOfertaLab.get(i).getIdArea();
					for (int j = 0; j < listaOfertaLab.size(); j++) {
						if (listaOfertaLab.get(j).getIdArea() == areaAnterior) {
							contador++;
						}
					}
					ds.addValue(contador, listaOfertaLab.get(i).getIdArea().getNombre(),
							listaOfertaLab.get(i).getIdArea().getNombre());
					contador = 0;
				}
			}

			JFreeChart jf = ChartFactory.createBarChart3D("Reporte de ofertas abiertas", "Nombre de las ofertas",
					"Numero de vacantes", ds, PlotOrientation.VERTICAL, true, true, true);

			panel = new ChartPanel(jf);
			panel.setBounds(20, 20, 720, 320);

			jPofertaabierta.add(panel);

		} catch (Exception e) {
			e.printStackTrace();
		}            
    }//GEN-LAST:event_jCProgramaAcademicoItemStateChanged

	public void reporteEgresadosOcupacion() {
		ChartPanel panel;
		try {
			List<InformacionLaboral> listaInfoLab = contReportes.listaInfomracionLaboral();

			double empleado = 0;
			double desempleado = 0;
			double independiente = 0;
			double empresario = 0;

			int contadorEmpleado = 0;
			int contadordDesempleado = 0;
			int contadorIndependiente = 0;
			int contadorEmpresario = 0;

			for (int i = 0; i < listaInfoLab.size(); i++) {
				if (listaInfoLab.get(i).getSitucionLaboral().equals("Empleado")) {
					contadorEmpleado++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Desempleado")) {
					contadordDesempleado++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Independiente")) {
					contadorIndependiente++;
				} else if (listaInfoLab.get(i).getSitucionLaboral().equals("Empresario")) {
					contadorEmpresario++;
				} else {
					JOptionPane.showMessageDialog(null, "No hay empleados registrados");
				}

				empleado = (contadorEmpleado * 100) / listaInfoLab.size();
				desempleado = (contadordDesempleado * 100) / listaInfoLab.size();
				independiente = (contadorIndependiente * 100) / listaInfoLab.size();
				empresario = (contadorEmpresario * 100) / listaInfoLab.size();
			}
			DefaultPieDataset ds = new DefaultPieDataset();
			ds.setValue("Empleado: " + empleado + "%", empleado);
			ds.setValue("Desempleado: " + desempleado + "%", desempleado);
			ds.setValue("Independiente: " + independiente + "%", independiente);
			ds.setValue("Empresario: " + empresario + "%", empresario);

			JFreeChart jf = ChartFactory.createPieChart3D("Reporte de egresados por tipo de ocupación", ds, true, true,
					true);

			panel = new ChartPanel(jf);
			panel.setBounds(20, 50, 720, 350);

			jPGraficaTipoOcupacion.add(panel);

		} catch (Exception e) {
			// TODO: handle exception
		}

	}

	/**
	 * Grafica de barras indicando la cnatidad de vacantes disponibles por
	 * oferta laboral
	 */
	public void ofertasAbriertas() {
		ChartPanel panel;
		try {
			List<OfertaLaboral> listaOfertaLab = contReportes.listaOfertaLab();

			int contador = 0;
			AreaInteres areaAnterior = null;
			DefaultCategoryDataset ds = new DefaultCategoryDataset();

			for (int i = 0; i < listaOfertaLab.size(); i++) {
				// Validacion de oferta
				if (listaOfertaLab.get(i).isCerrarOferta() == false) {
					areaAnterior = listaOfertaLab.get(i).getIdArea();
					for (int j = 0; j < listaOfertaLab.size(); j++) {
						if (listaOfertaLab.get(j).getIdArea() == areaAnterior) {
							contador++;
						}
					}
					ds.addValue(contador, listaOfertaLab.get(i).getIdArea().getNombre(),
							listaOfertaLab.get(i).getIdArea().getNombre());
					contador = 0;
				}
			}

			JFreeChart jf = ChartFactory.createBarChart3D("Reporte de ofertas abiertas", "Nombre de las ofertas",
					"Numero de vacantes", ds, PlotOrientation.VERTICAL, true, true, true);

			panel = new ChartPanel(jf);
			panel.setBounds(20, 20, 720, 320);

			jPofertaabierta.add(panel);

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * Genera tabla de los egresados de la eam que esten trabajando
	 */
	public void llenarTablaEmpleadosEmpresa() {
		try {
			DefaultTableModel df = (DefaultTableModel) jTEmpleadoEmpresa.getModel();
			df.setRowCount(0);

			List<InformacionLaboral> listaInfoLab = contReportes.listaInfomracionLaboral();

			for (int i = 0; i < listaInfoLab.size(); i++) {

				if (!listaInfoLab.get(i).getSitucionLaboral().equals("Desempleado")) {
					df.addRow(new Object[] {
							listaInfoLab.get(i).getEgresado().getNombre() + " "
									+ listaInfoLab.get(i).getEgresado().getApellido(),
							listaInfoLab.get(i).getEgresado().getPrograma().getNombrePrograma(),
							listaInfoLab.get(i).getCargoEmpresa(), listaInfoLab.get(i).getFechaIngreso() });
				}
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void llenarTablaOfertasPrograma() {
		try {
			DefaultTableModel df = (DefaultTableModel) jTreporteOfertaProgramas.getModel();
			df.setRowCount(0);

			List<OfertaLaboral> listOferta = contReportes.listaOfertaLab();

			for (int i = 0; i < listOferta.size(); i++) {
				if (listOferta.get(i).isCerrarOferta() == false) {
					df.addRow(new Object[] { listOferta.get(i).getIdempresa().getNombreEmpresa(),
							listOferta.get(i).getFechaoferta(), listOferta.get(i).getFechaofertaCierre(),
							listOferta.get(i).getCargoOfrecer(), listOferta.get(i).getSalario(),
							listOferta.get(i).getResumen() });
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void listaPrgrama() {
		
		try {
			List<Programa> listPrograma = contReportes.listaPrograma();
			jCPrograma.addItem((String)"Seleccione un programa");
			for (Programa programa : listPrograma) {
				jCPrograma.addItem(programa);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	public void listaPrgramaAcademico() {
		
		try {
			List<Programa> listPrograma = contReportes.listaPrograma();
			jCProgramaAcademico.addItem((String)"Seleccione un programa");
			for (Programa programa : listPrograma) {
				jCProgramaAcademico.addItem(programa);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCPrograma;
    private javax.swing.JComboBox jCProgramaAcademico;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPGraficaTipoOcupacion;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPofertaabierta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTEmpleadoEmpresa;
    private javax.swing.JTabbedPane jTPReportesYEstadisticas2;
    private javax.swing.JTable jTreporteOfertaProgramas;
    // End of variables declaration//GEN-END:variables
}
