/*
z * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.egresado.vista.gui;

/**
 *
 * @author laura posada
 */
public class VentanaPrincial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincial
     */
    public VentanaPrincial() {
        initComponents();    
         this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPOpcionesDeAplicacion = new javax.swing.JPanel();
        jBRegistroEgresados = new javax.swing.JButton();
        jBBolsaEmpleo = new javax.swing.JButton();
        jBParametrica = new javax.swing.JButton();
        jBInfEmpresa = new javax.swing.JButton();
        jBReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPOpcionesDeAplicacion.setBackground(new java.awt.Color(255, 255, 255));
        jPOpcionesDeAplicacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBRegistroEgresados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBRegistroEgresados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jBRegistroEgresados.setText("Registro Egresados");
        jBRegistroEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroEgresadosActionPerformed(evt);
            }
        });

        jBBolsaEmpleo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBBolsaEmpleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa de empleo.png"))); // NOI18N
        jBBolsaEmpleo.setText("Bolsa de Empelo");
        jBBolsaEmpleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBolsaEmpleoActionPerformed(evt);
            }
        });

        jBParametrica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBParametrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parametrica.png"))); // NOI18N
        jBParametrica.setText("Parametrica");
        jBParametrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBParametricaActionPerformed(evt);
            }
        });

        jBInfEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBInfEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion de la empresa.png"))); // NOI18N
        jBInfEmpresa.setText("Informacion de Empresa");
        jBInfEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInfEmpresaActionPerformed(evt);
            }
        });

        jBReportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jBReportes.setText("Reportes y Estadisticas");
        jBReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpcionesDeAplicacionLayout = new javax.swing.GroupLayout(jPOpcionesDeAplicacion);
        jPOpcionesDeAplicacion.setLayout(jPOpcionesDeAplicacionLayout);
        jPOpcionesDeAplicacionLayout.setHorizontalGroup(
            jPOpcionesDeAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesDeAplicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRegistroEgresados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBBolsaEmpleo)
                .addGap(29, 29, 29))
            .addGroup(jPOpcionesDeAplicacionLayout.createSequentialGroup()
                .addGroup(jPOpcionesDeAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOpcionesDeAplicacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBParametrica)
                        .addGap(27, 27, 27)
                        .addComponent(jBReportes))
                    .addGroup(jPOpcionesDeAplicacionLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBInfEmpresa)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPOpcionesDeAplicacionLayout.setVerticalGroup(
            jPOpcionesDeAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesDeAplicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpcionesDeAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistroEgresados)
                    .addComponent(jBBolsaEmpleo))
                .addGap(18, 18, 18)
                .addComponent(jBInfEmpresa)
                .addGap(32, 32, 32)
                .addGroup(jPOpcionesDeAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBParametrica)
                    .addComponent(jBReportes))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eam.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPOpcionesDeAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPOpcionesDeAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistroEgresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroEgresadosActionPerformed
        Egresados miEgresado = new Egresados();
        miEgresado.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jBRegistroEgresadosActionPerformed

    private void jBInfEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInfEmpresaActionPerformed
        VentanaEmpresa miEmpresa = new VentanaEmpresa();
       miEmpresa.setVisible(true);
    }//GEN-LAST:event_jBInfEmpresaActionPerformed

    private void jBBolsaEmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBolsaEmpleoActionPerformed
       BolsaEmpleo miBolsa = new BolsaEmpleo();
        miBolsa.setVisible(true);
    }//GEN-LAST:event_jBBolsaEmpleoActionPerformed

    private void jBParametricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBParametricaActionPerformed
        Parametrica miParametrica = new Parametrica();
        miParametrica.setVisible(true);
    }//GEN-LAST:event_jBParametricaActionPerformed

    private void jBReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReportesActionPerformed
        ReportesEstadisticas miReportesEstadisticas = new ReportesEstadisticas();
        miReportesEstadisticas.setVisible(true);
    }//GEN-LAST:event_jBReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBolsaEmpleo;
    private javax.swing.JButton jBInfEmpresa;
    private javax.swing.JButton jBParametrica;
    private javax.swing.JButton jBRegistroEgresados;
    private javax.swing.JButton jBReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPOpcionesDeAplicacion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
