insert into egresados.t_areainteres(ID_AREA,NOMBRE_AREA) values (77,'Desarrollo web')
insert into egresados.t_departamento(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO) values (33,'Tolima')
insert into egresados.t_ciudad(ID_CIUDAD,NOM_CIUDAD,ID_DEPARTAMENTO) values (88,'Ibague',33)
insert into egresados.t_sectorlaboral(ID_SECTORLABORAL,NOM_SECTORLABORAL) values (1,'Sinstemas informativos')
insert into egresados.t_empresa(ID_EMPRESA,CIUDAD,DEPARTAMENTO,DIRECCION,FAX,NIT,PAIS,RAZON_SOCIAL,SITIO_WEB,TELEFONO,TIPO_EMPRESA,ID_CIUDAD,ID_SECTOR) values (11,'Ibague','Tolima','cra 13','732','12345','Colombia','no se','cualquiercosa@gmail.com','33333','Privada',88,1)
