DELETE FROM t_info_academica  WHERE ID_EGRESADO = 1088
DELETE FROM t_egresado WHERE ID_EGRESADO = 1088
DELETE FROM egresados.t_programa WHERE ID_PROGRAMA = 15
DELETE FROM egresados.t_facultad WHERE ID_FACULTAD = 23